version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ${STORAGE_PATH}:/app/uploads
    environment:
      - PORT=$APPLICATION_PORT
      - ROOT_URL=${DOMAIN_ADDR}
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp
    depends_on:
      - mongo
      - nginx
    expose:
      - "$APPLICATION_PORT"
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: ${DOMAIN_ADDR}"
    ports:
      - "2222:22"
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - /mnt/volume_sfo2_01/data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo
  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certs:/opt/certs
    ports:
      - 80:80
      - 443:443
  smtp:
    image: namshi/smtp
    restart: always
    environment:
      RELAY_DOMAINS: rocketchat
      PORT: 25
      MAILNAME: chat.altamir.io
    expose:
      - 25
      - 465
      - 587  
